### PR TITLE
archive page

### PR DESCRIPTION
**Pull request by Aleksandar1231**
Created archive page displaying user's created surveys. Need a question template page to better display survey's questions

### CODE REVIEW

**Comment by austinjturner** [comment]
I've created a ton of surveys and my display was looking a little weird. What do you think of the image I've linked? If you think it makes sense to update it like that, you can update:

-  change `justify-content-around` to `justify-content-start` in archive.html line 36
- add to the css file 
```
.d-flex {
    overflow-x: auto;
}
``` 

image

**Comment by Aleksandar1231** [comment]
Much better, I must’ve forgot to add rows to the front end. I was thinking I’ve putting 3 surveys per row but a scroll pane is fine too

**Comment by Aleksandar1231** [comment]
I’ll make the cards a fixed height too

**Comment by austinjturner** [comment]
Yeah rows would work as well. When I opened the page, my surveys went right off the side of it. As long as it's not that, it should be good.

**Pull request merged**
